version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: marten_db
      POSTGRES_USER: marten_user
      POSTGRES_PASSWORD: marten_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: